songlabproject/songlab/urls.py
from  django.conf.urls import url
from songlab import views

urlpatterns = [
    url(r'^$',views.index,name='index'),#首页
    url(r'^services/$',views.services,name='services'),#科研成果
    url(r'^contact/$',views.contact,name='contact'),#其他
    url(r'^about/$',views.about,name='about'),#团队成员

]

songlabproject/songlabproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^songlab/',include('songlab.urls',namespace ='songlab')),
]

songlabproject/songlab/models.py
from django.db import models

# Create your models here.

songlabproject/songlab/views.py
from django.shortcuts import render


def about(request):

    return render(request,'songlab/about.html')

def index(request):

    return render(request,'songlab/index.html')

def contact(request):

    return  render(request,'songlab/contact.html')

def services(request):

    return render(request,'songlab/services.html')

songlabproject/templates/songlab/about.html
{% extends 'songlab_base.html' %}
{% load staticfiles %}
{% block title %} 团队成员 {% endblock %}


{% block content %}
    <!--  END Page Header  -->
                <div id="home-wrap" class="content-section fullpage-wrap">

                    <!-- Services Section -->
                    <div class="light-background">
                        <div class="container">
                            <div class="row no-margin padding-lg">
                                <div class="col-md-4 padding-leftright-null">
                                    <div class="text padding-topbottom-null padding-md-bottom">
                                        <i class="material-icons color service">硬件</i>
                                        <h3 class="margin-bottom-extrasmall">Experience</h3>
                                        <p class="margin-bottom-null">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.</p>
                                    </div>
                                </div>
                                <div class="col-md-4 padding-leftright-null">
                                    <div class="text padding-topbottom-null padding-md-bottom">
                                        <i class="material-icons color service">技术成果</i>
                                        <h3 class="margin-bottom-extrasmall">Goals</h3>
                                        <p class="margin-bottom-null">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.</p>
                                    </div>
                                </div>
                                <div class="col-md-4 padding-leftright-null">
                                    <div class="text padding-topbottom-null">
                                        <i class="material-icons color service">招生条件</i>
                                        <h3 class="margin-bottom-extrasmall">Vision</h3>
                                        <p class="margin-bottom-null">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- END Services Section -->
                    <!--  Team section  -->
                    <div class="container">
                        <div class="row no-margin padding-lg">
                            <div class="col-md-12 padding-leftright-null">
                                <div class="text text-center padding-topbottom-null">
                                    <h3 class="big">团队成员.</h3>
                                </div>
                            </div>
                            <!--  Team  -->
                            <div class="row team padding-onlytop-md">
                                <div class="col-xs-6 col-md-3 padding-leftright-null">
                                    <div class="person">
                                        <img src={% static "assets/img/songyan.jpg" %} alt="" class="img-responsive">
                                        <h3>宋艳老师</h3>
                                        <span>北京师范大学认知神经科学与学习国家重点实验室教授，博士生导师。</span>
                                        <span>于2003年获中国科学院生物物理研究所生物物理专业理学博士学位；1997年在首都医科大
                                            学获生物医学工程工学学士学位。2010年在美国加州大学（San Diego）做访问学者。
                                            主持的科研项目包括国家自然科学基金面上项目（2007年，2010年，2013年）、北京市自
                                            然科学基金（2007年）等，参与的科研项目包括国家重点基础研究发展计划（2009年，2014年）
                                            等，获北京师范大学励耘青年教师奖， “京师英才”等多项奖励。已经发表30多篇英文学术论文，
                                            是NeuroImage，Human Brain Mapping，Scientific Reports，Vision Research等多个专业学术期刊的审稿人。</span>
                                    </div>
                                </div>
                                <div class="col-xs-6 col-md-3 padding-leftright-null">
                                    <div class="person">
                                        <img src={% static "assets/img/zhaochenguang.jpg" %} alt="" class="img-responsive">
                                        <h3>赵晨光</h3>
                                        <span>本科:郑州大学.通信工程</span>
                                        <span>研究生:北京师范大学.基础心理</span>
                                        <span>1.EEG-fNIRS多模态记录</span>
                                        <span>2.儿童ADHD脑电与眼动研究</span>
                                        <span>3.基础视觉以及注意机制的研究</span>

                                    </div>
                                </div>
                                <div class="col-xs-6 col-md-3 padding-leftright-null">
                                    <div class="person">
                                        <img src={% static "assets/img/libingkun.jpg" %} alt="" class="img-responsive">
                                        <h3>李秉坤</h3>
                                        <span>本科(2013-2017):广州大学.心理系</span>
                                        <span>研究生(在读):北京师范大学.基础心理</span>

                                    </div>
                                </div>
                                <div class="col-xs-6 col-md-3 padding-leftright-null">
                                    <div class="person">
                                        <img src={% static "assets/img/liweidong.jpg" %} alt="" class="img-responsive">
                                        <h3>李东韡</h3>
                                        <span>本科：江苏大学.物理系</span>
                                        <span>1.视觉加工与注意的脑机制研究；</span>
                                        <span>2.视觉空间注意与工作记忆的脑机制研究；</span>
                                        <span>3.EEG-fNIRS-saccade多模态视觉研究</span>

                                    </div>
                                </div>
                            </div>
                            <div class="row team padding-onlytop-md">
                                <div class="col-xs-6 col-md-3 padding-leftright-null">
                                    <div class="person">
                                        <img src={% static "assets/img/guojialiang.jpg" %} alt="" class="img-responsive">
                                        <h3>郭家梁</h3>
                                        <span>本科:河北工程大学，自动化</span>
                                        <span>北京工业大学，控制科学与工程/北京师范大学</span>
                                        <span>1.基于脑电的儿童视知觉及注意机理研究</span>
                                        
                                    </div>
                                </div>
                                <div class="col-xs-6 col-md-3 padding-leftright-null">
                                    <div class="person">
                                        <img src={% static "assets/img/libingkun.jpg" %} alt="" class="img-responsive">
                                        <h3>李秉坤</h3>
                                        <span>暂无</span>

                                    </div>
                                </div>
                                <div class="col-xs-6 col-md-3 padding-leftright-null">
                                    <div class="person">
                                        <img src={% static "assets/img/taoye.jpg" %} alt="" class="img-responsive">
                                        <h3>陶烨</h3>
                                        <span>本科:北京航空航天大学，数学系</span>
                                        <span>1.EEG-fNIRS多模态记录 </span>
                                        <span>2.基础视觉以及注意机制的研究</span>

                                    </div>
                                </div>
                                <div class="col-xs-6 col-md-3 padding-leftright-null">
                                    <div class="person">
                                        <img src={% static "assets/img/wangencong.jpg" %} alt="" class="img-responsive">
                                        <h3>王恩聪</h3>
                                        <span>本科:济宁医学院，精神病与精神卫生</span>
                                        <span>研究生:北京大学第六医院/北京师范大学</span>
                                        <span>研究方向:ADHD儿童视空间脑机制研究</span>


                                    </div>
                                </div>

                            </div>
                            <div class="row team padding-onlytop-md">
                                <div class="col-xs-6 col-md-3 padding-leftright-null">
                                    <div class="person">
                                        <img src={% static "assets/img/changxinyuan.jpg" %} alt="" class="img-responsive">
                                        <h3>常勤缘(照片太小)</h3>
                                        <span>暂无</span>

                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
{% endblock %}



        


songlabproject/templates/songlab/contact.html
{% extends 'songlab_base.html' %}
{% load staticfiles %}

{% block title %} 联系我们 {% endblock %}
 {% block header-Content  %}{% endblock %}

{% block content %}
                <!--  Page Header  -->
                <div id="page-header" class="secondary-background">
                    <div class="container">
                        <div class="row no-margin">
                            <div class="text">
                                <h1 class="white">联系我们.</h1>
                                <ul class="breadcrumb white">
                                    <li><a href="#">主页</a></li>
                                    <li>联系我们</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!--  END Page Header  -->
                <div id="home-wrap" class="content-section fullpage-wrap">
                    <!--  Contact section  -->
                    <div class="container">
                        <div class="row no-margin padding-lg">
                            <div class="col-md-12 padding-leftright-null">
                                <div class="text text-left padding-topbottom-null">
                                    <h2>留言.</h2>
                                </div>
                            </div>
                            <div class="row no-margin padding-onlytop-md">
                                <!--  Contact Form  -->
                                <div class="col-md-5 padding-leftright-null">
                                    <div class="text padding-md-top-null">
                                        <div class="box-form">
                                            <form id="contact-form">
                                                <div class="row no-margin">
                                                    <div class="col-md-12 padding-leftright-null">
                                                        <label for="name">Name<sup>*</sup></label>
                                                        <input class="form-field" name="name" id="name" type="text" placeholder="Your Name">
                                                    </div>
                                                    <div class="col-md-12 padding-leftright-null">
                                                        <label for="mail">Email<sup>*</sup></label>
                                                        <input class="form-field" name="mail" id="mail" type="text" placeholder="Your Email">
                                                    </div>
                                                </div>
                                                <div class="row no-margin">
                                                    <div class="col-md-12 padding-leftright-null">
                                                        <label for="messageForm">Message<sup>*</sup></label>
                                                        <textarea class="form-field" name="messageForm" id="messageForm" rows="6" placeholder="Your Message"></textarea>
                                                        <div class="submit-area padding-onlytop-sm">
                                                            <input type="submit" id="submit-contact" class="btn-alt active shadow" value="Send Message">
                                                            <div id="msg" class="message"></div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <!--  END Contact Form  -->
                                <!--  Contact Info  -->
                                <div class="col-md-7 padding-leftright-null">
                                    <div class="row no-margin padding-onlytop-md">
                                        <div class="col-md-6 padding-leftright-null">
                                            <div class="text padding-md-top-null">
                                                <h3 class="margin-bottom-small">Come Visit</h3>
                                                <p class="margin-null">322 Moon St, Venice Italy, 1231</p>
                                            </div>
                                        </div>
                                        <div class="col-md-6 padding-leftright-null">
                                            <div class="text padding-md-top-null">
                                               <h3 class="margin-bottom-small">Give Us a call</h3>
                                                <p class="margin-bottom-extrasmall"><a href="" class="simple">+1 234 5678 901
                                                   </a></p>
                                               <p class="margin-null"><a href="" class="simple">+1 456 7890 1234</a></p>
                                           </div>
                                        </div>
                                    </div>
                                    <div class="row no-margin">
                                        <div class="col-md-6 padding-leftright-null">
                                            <div class="text padding-md-top-null">
                                                <h3 class="margin-bottom-small">Email Us</h3>
                                                <p class="margin-bottom-extrasmall"><a href="" class="simple">info@bussible.com</a></p>
                                                <p class="margin-null"><a href="" class="simple">hello@bussible.com</a></p>
                                            </div>
                                        </div>
                                        <div class="col-md-6 padding-leftright-null">
                                            <div class="text padding-md-top-null padding-md-bottom-null">
                                                <h3 class="margin-bottom-small">Start a project with us</h3>
                                                <p class="margin-bottom-extrasmall">Lorem ipsum dolor sit amet.</p>
                                                <p class="margin-null">Lorem ipsum dolor!</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!--  END Contact Info  -->
                            </div>
                        </div>
                    </div>
                    <!--  END Contact section  -->
                    <div class="row no-margin">
                        <!--  Map. Settings in maps.js  -->
                        <div class="col-md-12 padding-leftright-null map">
                            <div id="map"></div>
                        </div>
                        <!--  END Map  -->
                    </div>
                </div>
 {% endblock %}

songlabproject/templates/songlab_base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title  %} {% endblock %}</title>

        <link href="{% static "assets/img/beishidalogo.png" %}" rel="shortcut icon">

        <!-- Bootstrap -->
        <link rel="stylesheet" href={% static "assets/css/bootstrap/bootstrap.min.css" %}>

        <!-- Optional theme -->
        <link rel="stylesheet" href={% static "assets/css/bootstrap/bootstrap-theme.min.css" %}>

        <!-- Custom css -->
        <link rel="stylesheet" href={% static "assets/css/style.css" %}>

        <!-- Font Awesome -->
        <link rel="stylesheet" type="text/css" href="http://www.jq22.com/jquery/font-awesome.4.6.0.css">

        <link rel="stylesheet" href={% static "assets/css/ionicons.min.css" %}>

        <!-- Flexslider -->
        <link rel="stylesheet" href={% static "assets/css/flexslider.css" %}>

        <!-- Owl -->
        <link rel="stylesheet" href={% static "assets/css/owl.carousel.css" %}>

        <!-- Magnific Popup -->
        <link rel="stylesheet" href={% static "assets/css/magnific-popup.css" %}>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>

        <!--  loader  -->
        <div id="myloader">
            <div class="loader">
                <div class="grid">
                    <div class="cube cube1"></div>
                    <div class="cube cube2"></div>
                    <div class="cube cube3"></div>
                    <div class="cube cube4"></div>
                    <div class="cube cube5"></div>
                    <div class="cube cube6"></div>
                    <div class="cube cube7"></div>
                    <div class="cube cube8"></div>
                    <div class="cube cube9"></div>
                </div>
            </div>
        </div>

        <!--  Header & Menu  -->
        <header id="header">
            <div class="top-nav">
                <!--  Header Logo  -->
                <div id="logo">
                    <a class="navbar-brand" href="index.html">
                        <img src="{% static "assets/img/songLabLogo.png" %}" class="normal" alt="logo">
                        <img src={% static "assets/img/songLabLogo.png" %} class="retina" alt="logo">
                    </a>
                </div>
                <!--  END Header Logo  -->
                <div class="secondary-menu">
                    <ul>
                        <li class="mail"><i class="fa fa-envelope" aria-hidden="true"></i><a href="maito:info@domain.com">info@domain.com</a></li>
                        <li class="phone"><i class="fa fa-phone" aria-hidden="true"></i>+39 123456789</li>
                        {% block  language%}
                        <li class="lang">
                            <span class="current"><a href="about_EN.html">En</a></span>
                            <ul>
                                <li><a href="#">It</a></li>
                            </ul>
                        </li>
                        {% endblock %}
                        <!-- Search Icon -->
                        <!--<li class="search">
                            <i class="fa fa-search" aria-hidden="true"></i>
                        </li>-->
                    </ul>
                </div>
            </div>
            <nav class="navbar navbar-default">
                <!--  Classic menu, responsive menu classic  -->
                <div id="menu-classic">
                    <div class="menu-holder">
                        <ul>
                            <li><a href={% url 'songlab:index' %}>主页</a></li>
                            <li><a href={% url 'songlab:about' %}>团队成员</a></li>
                            <li><a href={% url 'songlab:services' %}>科研成果</a></li>
                            <li><a href={% url 'songlab:contact' %}>其他</a></li>
                        </ul>
                    </div>
                </div>
                <div id="menu-responsive-classic">
                    <div class="menu-button">
                        <span class="bar bar-1"></span>
                        <span class="bar bar-2"></span>
                        <span class="bar bar-3"></span>
                    </div>
                </div>
                <!--  END Button for Responsive Menu Classic  -->
                <div class="secondary-menu-mobile">
                    <ul>
                        <li class="mail"><i class="fa fa-envelope" aria-hidden="true"></i><a href="maito:info@domain.com">info@domain.com</a></li>
                        <li class="phone"><i class="fa fa-phone" aria-hidden="true"></i>+39 123456789</li>
                        <li class="lang">
                            <span class="current"><a href="#">En</a></span>
                            <ul>
                                <li><a href="#">It</a></li>
                            </ul>
                        </li>
                        <!-- Search Icon -->
                        <li class="search">
                            <i class="fa fa-search" aria-hidden="true"></i>
                        </li>
                    </ul>
                </div>
            </nav>


            <div id="header-searchform">
                <form class="search-form">
                    <div class="form-input">
                        <input type="text" placeholder="Search...">
                        <span class="form-button-close">
                            <button type="button"><i class="material-icons">close</i></button>
                        </span>
                        <span class="form-button">
                            <button type="button">Search</button>
                        </span>
                    </div>
                </form>
            </div>
        </header>
        <!--  END Header & Menu  -->

        <!--  Main Wrap  -->
        <div id="main-wrap">
            <!--  Page Content  -->
            <div id="page-content" class="header-static">
            {% block header-Content  %}
                <!--  Page Header  -->
                <div id="page-header" class="secondary-background">
                    <div class="container">
                        <div class="row no-margin">
                            <div class="text">
                                <h1 class="white">我们团队.</h1>
                                <ul class="breadcrumb white">
                                    <li><a href="#">主页</a></li>
                                    <li>团队成员</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
    {% endblock %}
        {% block content %}{% endblock %}
            </div>
        </div>


        <footer>
            <div class="container">
                <div class="row no-margin">
                    <div class="col-md-3 text">
                        <div class="logo">
                            <img src={% static "assets/img/songLabLogo.png" %} class="normal" alt="logo">
                            <img src={% static "assets/img/songLabLogo.png" %} class="retina" alt="logo">
                        </div>
                        <p>这里可以在对你们实验室做一个简单的介绍要是没有我就删了. </p>

                    </div>
                    <div class="col-md-3 text small">
                        <h4 class="heading white margin-bottom-small weight-300">实 验 室</h4>
                        <p>科研 创新<br>
                            <br>
                            周一~周五， 9:00  - 18.00 </p>
                    </div>
                    <div class="col-md-2 text small">
                        <h4 class="heading white margin-bottom-small weight-300">链接我们</h4>
                        <ul class="info">
                            <li><a href={% url 'songlab:index' %}>主页</a></li>
                            <li><a href={% url 'songlab:about' %}>团队成员</a></li>
                            <li><a href={% url 'songlab:services' %}>科研成果</a></li>
                            <li><a href={% url 'songlab:contact' %}>其他</a></li>
                        </ul>
                    </div>
                    <div class="col-md-4 text">
                        <h4 class="heading white margin-bottom-small weight-320">认知神经科学与学习国家重点实验室-北京师范大学.</h4>
                        <p>电话（传真）：86-10-58806154 </br>邮箱：keylab@bnu.edu.cn </p>
                        <p>地址：北京市海淀区新街口外大街19号 英东楼 </br>邮编：100875 </p>

                    </div>
                </div>
            </div>
        </footer>

        <div id="copy">
            <div class="container">
                <div class="row no-margin">
                    <div class="col-md-6 text">
                        <p>Copyright © 2017 . All Rights Reserved </p>
                    </div>

                </div>
            </div>
        </div>

        <script src={% static "assets/js/jquery.min.js" %}></script>
        <!-- All js library -->
        <script src={% static "assets/js/bootstrap/bootstrap.min.js" %}></script>
        <script src={% static "assets/js/jquery.flexslider-min.js" %}></script>
        <script src={% static "assets/js/owl.carousel.min.js" %}></script>
        <script src={% static "assets/js/isotope.min.js" %}></script>
        <script src={% static "assets/js/jquery.magnific-popup.min.js" %}></script>
        <!---<script src="http://ditu.google.cn/maps/api/js?v=3.exp&signed_in=false"></script>--->
        <script src={% static "assets/js/jquery.scrollTo.min.js" %}></script>
        <script src={% static "assets/js/smooth.scroll.min.js" %}></script>
        <script src={%  static "assets/js/jquery.appear.js" %}></script>
        <script src={% static "assets/js/jquery.countTo.js" %}></script>
        <script src={% static "assets/js/jquery.scrolly.js" %}></script>
        <script src={% static "assets/js/plugins-scroll.js" %}></script>
        <script src={%  static "assets/js/imagesloaded.min.js" %}></script>
        <script src={% static "assets/js/pace.min.js" %}></script>
        <script src={% static "assets/js/main.js" %}></script>

    </body>

</html>